version: '2'

services:
  mysqldb:
    image: mysql:latest
    environment:
      - "MYSQL_ROOT_PASSWORD=gotest"
      - "MYSQL_DATABASE=gotest"
      - "MYSQL_USER=gotest"
      - "MYSQL_PASSWORD=gotest"
    volumes:
      - "./db/data:/var/lib/mysql"

  admin-panel:
    build:
      context: ./admin-panel/
      dockerfile: Dockerfile
    image: etixtv/admin-panel
    ports:
      - "3000:3000"
    volumes:
      - "./admin-panel:/usr/src/app"

  viewer:
    build:
      context: ./viewer/
      dockerfile: Dockerfile
    image: etixtv/viewer
    ports:
      - "3042:3000"
    volumes:
      - "./viewer:/usr/src/app"

  s3:
    image: minio/minio
    ports:
      - "9001:9000"
    volumes:
      - ./s3/data:/export
      - ./s3/config:/root/.minio
    environment:
      - "MINIO_ACCESS_KEY=HS4SFCA35UZHNW3YBHOT"
      - "MINIO_SECRET_KEY=k9gkHCeMqGB83TKgqIOn38KXmgfpaNEBgQTucXHH"
      # - MINIO_REGION="luxembourg"
    command: server /export

  static-provider:
    image: halverneus/static-file-server:latest
    ports:
      - "8080:8080"
    volumes:
      - ./s3/data/media:/web

  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    image: etixtv/api
    ports:
      - "4242:4242"
      - "4244:4244"
    links:
      - mysqldb
    depends_on:
      - "s3"
    volumes:
      - "./api:/go/src/etix-tv-manager/api"
    command: gin -i -p 4244 -a 4242
