version: '2'

services:
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    image: etixtv/api
    ports:
      - "4242:4242"
      - "4244:4244"
    volumes:
      - "./api:/go/src/etix-tv-manager/api"
    command: gin -p 4244 -a 4242

  admin-panel:
    build:
      context: ./admin-panel/
      dockerfile: Dockerfile
    image: etixtv/admin-panel
    ports:
      - "3000:3000"
    volumes:
      - "./admin-panel:/usr/src/app"

  s3:
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - ./s3/data:/export
      - ./s3/config:/root/.minio
    environment:
      - "MINIO_ACCESS_KEY=HS4SFCA35UZHNW3YBHOT"
      - "MINIO_SECRET_KEY=k9gkHCeMqGB83TKgqIOn38KXmgfpaNEBgQTucXHH"
    command: server /export
