version: '2'

services:
  mysqldb:
    image: mysql:latest
    environment:
      - "MYSQL_ROOT_PASSWORD=k9gkHCeMqGB83TKgqIOn38KXmgfpaNEBgQTucXHH"
      - "MYSQL_DATABASE=etixtv"
      - "MYSQL_USER=etix"
      - "MYSQL_PASSWORD=HS4SFCA35UZHNW3YBHOT"
    volumes:
      - "./db/data:/var/lib/mysql"

  admin-panel:
    build:
      context: ./admin-panel/
      dockerfile: Dockerfile
    image: etixtv/admin-panel
    environment:
      - "REACT_APP_API_URL=http://127.0.0.1:4244"
      - "REACT_APP_STATIC_URL=http://127.0.0.1:8080/"
    ports:
      - "3000:3000"
    volumes:
      - "./admin-panel:/usr/src/app"

  viewer:
    build:
      context: ./viewer/
      dockerfile: Dockerfile
    image: etixtv/viewer
    environment:
      - "REACT_APP_API_URL=http://127.0.0.1:4244"
      - "REACT_APP_STATIC_URL=http://127.0.0.1:8080/"
    ports:
      - "3042:3000"
    volumes:
      - "./viewer:/usr/src/app"

  s3:
    image: minio/minio
    volumes:
      - ./s3/data:/export
      - ./s3/config:/root/.minio
    environment:
      - "MINIO_ACCESS_KEY=HS4SFCA35UZHNW3YBHOT"
      - "MINIO_SECRET_KEY=k9gkHCeMqGB83TKgqIOn38KXmgfpaNEBgQTucXHH"
    command: server /export

  static-provider:
    image: halverneus/static-file-server:latest
    ports:
      - "8080:8080"
    volumes:
      - ./s3/data/media:/web

  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    image: etixtv/api
    hostname: "api"
    ports:
      - "4242:4242"
      - "4244:4244"
    environment:
      - "DATABASE_URL=mysqldb"
      - "DATABASE_PORT=3306"
      - "DATABASE_USER=etix"
      - "DATABASE_PASSWORD=HS4SFCA35UZHNW3YBHOT"
      - "DATABASE_NAME=etixtv"
      - "S3_URL=mediaserver"
      - "S3_PORT=9000"
      - "S3_ACCESS_KEY=HS4SFCA35UZHNW3YBHOT"
      - "S3_SECRET_KEY=k9gkHCeMqGB83TKgqIOn38KXmgfpaNEBgQTucXHH"
    links:
      - "mysqldb"
      - "s3:mediaserver"
    depends_on:
      - "s3"
      - "mysqldb"
    volumes:
      - "./api:/go/src/etix-tv-manager/api"
    command: gin -i -p 4244 -a 4242
