FROM node:6

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

#ADD ./package.json /usr/src/app
#RUN npm install
#ADD ./src /usr/src/app/src
#ADD ./public /usr/src/app/public

CMD ["npm", "run", "start"]
